language: go
go:
  - 1.3
  - 1.4
  - tip
node_js:
  - "0.10"

install:
  - go get -v -t ./...
  - pushd regbackend && go build -v && popd
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm start > /dev/null &
  - cd regbackend && ./regbackend -http.listen=localhost:9090 >/dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - go test -v ./...
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor e2e-tests/protractor.conf.js --browser=firefox
