language: go
go:
  - 1.7
  - tip

cache:
  directories:
    - npm_modules

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9
  firefox: "latest"
  sauce_connect:
    username: "timber"
  jwt:
    secure: "clRdwXlRjqqd0KgYzetirIaun05veeMlMtPtnoW4yWmZ/sZ3xl1GmRI4QxJ9Vk6nDa2k1JaYuQvxuSY0nN+OfWkb7LlkJJu8xaourItjhuA7O3Ro7qPLRFFfDGmC161yXj+2k18BoFmsTPMe7rzKPU2TcgfLqI1yWG4Dkbrkd2w="

install:
  - nvm install stable
  - nvm use stable
  - export CC="gcc-4.9" export CXX="g++-4.9" LINK="gcc-4.9" LINKXX="g++-4.9"
  - node --version
  - gcc --version
  - go get -v -t ./...
  - pushd regbackend && go build -v && go build -v -tags integration && popd
  - npm install
  - npm update
  - npm install -g grunt-cli

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - grunt -v jshint build
  - cd regbackend && ./regbackend -flagfile=flags.test --staticfileslocation=../dist >/dev/null &
  - npm run update-webdriver
  - sleep 1 # give server time to start

script:
  - go test -v ./...
  - node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - node_modules/.bin/protractor protractor.conf.js --browser=firefox
  - node_modules/.bin/karma start karma-remote.conf.js --no-auto-watch --single-run --reporters=dots,saucelabs
  - node_modules/.bin/protractor protractor-remote.conf.js

after_script:
  - killall regbackend
